### ISSUE TITLE
on_ruby help

### ISSUE THREAD

**Issue by phoet** [madridrb/madridrb.org#18]
if you want to adopt [on_ruby](https://github.com/phoet/on_ruby) feel free to ping me, i can help you get setup in no time.

happy new year!

**Comment by kikito** [comment]
Hi, happy new year to you too!

I will study on_ruby to see wether it matches our needs - it seems to do so, but I only gave it a cursory look; saw that the test passed on my machine, that kind of thing.

If I have any questions, I will let you know.

One of the first things I will do is translating it to Spanish. Would you be interested in getting the locale files in Spanish? I can send a PR.

**Comment by phoet** [comment]
@kikito if you need anything, let me know. having the spanish locale would be great.

just a bit of context:

the app is currently hosted on heroku and runs as a multi-tenancy app. so if you don't want to host it yourself, you can just integrate it with all the other apps, we just need to do some DNS stuff to hook it up properly.

most of the functionality is pretty simplistic and that is on purpose. most of the features that we thought of havn't proven to be worth the code, so a lot has been removed. if you need anything special, let me know and we can find a way to implement it easily.

**Comment by kikito** [comment]
> having the spanish locale would be great.

Alright :)

I will get to it this evening.

>  if you don't want to host it yourself, you can just integrate it with all the other apps, we just need to do some DNS stuff to hook it up properly.

That's always an option, I will get back to you on that.

> if you need anything special, let me know and we can find a way to implement it easily.

I will, thanks :)

**Comment by kikito** [comment]
Ok, I just sent you a PR with the es locale (it was bigger than I thought).

I have some comments regarding the functionality of the page for madrid-rb. We're missing some. In particular:
- As a group, Madrid.rb has sponsors. Our compromise with them stipulates that we'll put a link with their logo in all the talks they sponsorize. The most basic way to accomplish this that I can think of is a "footer field" added by the admins on the talk, made in markdown, like the description. A more "elaborate" thing would be having a Sponsor model.
- We also have videos of the talks we give (they are hosted in Vimeo). The video of a talk usually gets uploaded 1 month after the talk is done. It would be very nice if we could play it embedded on the event's page. Again, we could do this with a "admin field" on the event model. Or I could have a Video model.

Also, some "nice to haves":
- I had to use the English term "Mailing List" instead of the Spanish term "Lista de Correo" because it was too long on the header, and the hamburguer menu "overflowed". So I have been looking for items to remove on the list. For example: do we really need a "People" item in the nav? The paragraph it points to could be put at the beginning of the view, without needing its own section.
- Am I right to assume that the style (the css) and views are shared by all the groups? The unordered lists "Armenian style" look out of place in Spanish, and I would probably add more protagonism to the Videos.

I think I can add the functionality I need and the "nice to have". But I am telling them to you because they condition other things. For example, if you don't want this functionality on the core of on_ruby, we would have to fork it and host our own server (no hard feelings). If you do, then I can send you PRs for these things, but we have to decide which way is better for your groups (i.e. a simple markdown entry for the admins vs a Sponsor model).

Hope I made myself clear. Thanks for your support!

**Comment by phoet** [comment]
@kikito thx for the feedback, the spanish version is :ship: already!

berlin usergroup (rug-b) uses some css/js to add a general sponsor logo:

![screen shot 2015-01-07 at 10 19 32](https://cloud.githubusercontent.com/assets/48745/5643306/d63bfb88-9656-11e4-8b69-24273fe36fc5.png)

every usergroup can add custom images/css/js so you can fix/customize thing that overflow etc.

for the customizations like sponsor and video model i would like to see if it's feasible for you to start with inlining it in the markdown. if that does not work, we can for sure add more functionality/models.

in terms of videos, we have additional "material" that is associated to a talk which can also be a video that we could make embedded.

**Comment by kikito** [comment]
> thx for the feedback, the spanish version is :ship: already!

wow, you are fast :)

I'm going to start working on the PR to have madrid.rb in on_rails then.

One more thing: I'd like to migrate the past events we've had in the past to the on_rails website. What would be the preferred way to do this? The data of the previous meetings is in markdown, but I can parse it and transform it into a yaml if that makes things easier.

**Comment by phoet** [comment]
@kikito i can give you heroku admin access if necessary, that would probably be the simplest thing.

**Comment by phoet** [comment]
there has been some active development for rails 4.2 so it would be good for you to rebase against master

**Comment by kikito** [comment]
Thanks! I could rebase without conflicts. I've had some trouble doing the branch (i.e. we don't have a TLD domain and have to purchase one, also had to make some more changes to the code). But we'll make it.

**Comment by phoet** [comment]
technically you don't need a TLD because everything is accessible through label-id.onruby.de|at. i would have bought .es as well, but my registrar does not do spanish domains...
